---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-capi-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  - serviceaccounts
  verbs:
  - create
  - get
  - patch
